### ISSUE TITLE
[BUILD ERROR] unable to compile on fedora 35 

### ISSUE THREAD

**Issue by nesper8** [scp-fs2open/wxLauncher#169]
```
nesper8@fedora build  $ make -j4
Checking if build is needed...
 /home/nesper8/Projects/wxLauncher-release-0.10.0/build/version.cpp.maker.temp does not exist
Generating...
 Writing to tempfile /home/nesper8/Projects/wxLauncher-release-0.10.0/build/version.cpp.maker.temp.
  Directory already exists...
  File "/home/nesper8/Projects/wxLauncher-release-0.10.0/scripts/onlinehelpmaker.py", line 17
    print "ERROR: Unable to import markdown the markup parser."
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
make[2]: *** [CMakeFiles/helpmaker.dir/build.make:70: CMakeFiles/helpmaker] Error 1
make[1]: *** [CMakeFiles/Makefile2:113: CMakeFiles/helpmaker.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Traceback (most recent call last):
  File "/home/nesper8/Projects/wxLauncher-release-0.10.0/scripts/version.cpp.maker.py", line 41, in <module>
    main(sys.argv)
  File "/home/nesper8/Projects/wxLauncher-release-0.10.0/scripts/version.cpp.maker.py", line 29, in main
    maker.build()
  File "/home/nesper8/Projects/wxLauncher-release-0.10.0/scripts/version_file_builder.py", line 58, in build
    out.write('const wchar_t *GITVersion = L"')
TypeError: a bytes-like object is required, not 'str'
make[2]: *** [CMakeFiles/version.cpp.maker.dir/build.make:70: CMakeFiles/version.cpp.maker] Error 1
make[1]: *** [CMakeFiles/Makefile2:87: CMakeFiles/version.cpp.maker.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

```

**Comment by jg18** [comment]
Hi,

Thanks for your interest in wxLauncher. However, it's been superseded by [Knossos](https://fsnebula.org/knossos/), so please take a look at that instead.

For help building Knossos on Linux, I suggest seeking support from the Hard Light Productions (HLP) community. Please see the [HLP forums' Knossos  thread](https://www.hard-light.net/forums/index.php?topic=94068.0), or join the #knossos channel on the HLP Discord server (link is reachable from the top navigation bar in the HLP forums).

Thanks again!

**Comment by jg18** [comment]
For building Knossos, while these [build instructions](https://github.com/ngld/old-knossos/wiki/Building-instructions) are slightly outdated, they should point you in the right direction. For further help, please check with the HLP community, as described above.
